-- =============================================================================
-- seed.sql — Optional / Demo Data Only
-- =============================================================================
-- Convention:
--   Infrastructure data (roles, permissions, default org) lives in migrations.
--   This file contains ONLY optional demo/test data.
--
-- This file runs after all migrations during `supabase db reset`.
-- It must be safe to skip in production.
-- =============================================================================

-- No demo data required for initial deployment.
-- Future entries: demo courses, test categories, sample notifications.
