const fs = require('fs');
let c = fs.readFileSync('src/pages/CoursesPage.tsx', 'utf8');
c = c.replace(/course\.category_id/g, 'course.id');
c = c.replace(/c\.category_id/g, 'c.id');
c = c.replace(/course\.duration/g, '0');
c = c.replace(/course\.short_description/g, 'course.description');
c = c.replace(/c\.price/g, '0');
c = c.replace(/course\.price/g, '0');
c = c.replace(/0 > 0 \? `.*?` : "Free"/g, '"Free"');
fs.writeFileSync('src/pages/CoursesPage.tsx', c);
