// Real CRUD + reorder for mentor-managed profile content (experience/projects/
// certifications/achievements) - replaces the fabricated data previously
// generated by mentorProfileFactory.ts. Follows curriculum.service.ts's exact
// conventions: typed via Tables<>/Inserts<>/Updates<>, auto-assigned sort_order,
// soft delete via deleted_at, batch reorder via Promise.all.
import type { Inserts, Tables, Updates } from "@/types/database";
import { assertServiceResponse, getSupabaseClientOrThrow } from "./_shared";

export type MentorExperienceRow = Tables<"mentor_experience">;
export type MentorProjectRow = Tables<"mentor_projects">;
export type MentorCertificationRow = Tables<"mentor_certifications">;
export type MentorAchievementRow = Tables<"mentor_achievements">;

export type MentorExperienceInput = Inserts<"mentor_experience">;
export type MentorProjectInput = Inserts<"mentor_projects">;
export type MentorCertificationInput = Inserts<"mentor_certifications">;
export type MentorAchievementInput = Inserts<"mentor_achievements">;

async function nextSortOrder(table: "mentor_experience" | "mentor_projects" | "mentor_certifications" | "mentor_achievements", mentorId: string) {
  const supabase = getSupabaseClientOrThrow();
  const { count } = await supabase
    .from(table)
    .select("id", { count: "exact", head: true })
    .eq("mentor_id", mentorId)
    .is("deleted_at", null);
  return count ?? 0;
}

// ─── Experience ───────────────────────────────────────────────────────────────

export async function listMentorExperience(mentorId: string): Promise<MentorExperienceRow[]> {
  const supabase = getSupabaseClientOrThrow();
  const { data, error } = await supabase
    .from("mentor_experience")
    .select("*")
    .eq("mentor_id", mentorId)
    .is("deleted_at", null)
    .order("sort_order", { ascending: true });
  assertServiceResponse(error);
  return data ?? [];
}

export async function createMentorExperience(input: MentorExperienceInput): Promise<MentorExperienceRow> {
  const supabase = getSupabaseClientOrThrow();
  const finalInput = input.sort_order === undefined
    ? { ...input, sort_order: await nextSortOrder("mentor_experience", input.mentor_id) }
    : input;
  const { data, error } = await supabase.from("mentor_experience").insert(finalInput).select("*").single();
  assertServiceResponse(error);
  return data;
}

export async function updateMentorExperience(id: string, input: Updates<"mentor_experience">): Promise<MentorExperienceRow> {
  const supabase = getSupabaseClientOrThrow();
  const { data, error } = await supabase.from("mentor_experience").update(input).eq("id", id).select("*").single();
  assertServiceResponse(error);
  return data;
}

export async function deleteMentorExperience(id: string): Promise<void> {
  const supabase = getSupabaseClientOrThrow();
  const { error } = await supabase.from("mentor_experience").update({ deleted_at: new Date().toISOString() }).eq("id", id);
  assertServiceResponse(error);
}

export async function reorderMentorExperience(mentorId: string, orderedIds: string[]): Promise<void> {
  const supabase = getSupabaseClientOrThrow();
  await Promise.all(
    orderedIds.map((id, index) =>
      supabase.from("mentor_experience").update({ sort_order: index }).eq("id", id).eq("mentor_id", mentorId)
    )
  );
}

// ─── Projects ─────────────────────────────────────────────────────────────────

export async function listMentorProjects(mentorId: string): Promise<MentorProjectRow[]> {
  const supabase = getSupabaseClientOrThrow();
  const { data, error } = await supabase
    .from("mentor_projects")
    .select("*")
    .eq("mentor_id", mentorId)
    .is("deleted_at", null)
    .order("sort_order", { ascending: true });
  assertServiceResponse(error);
  return data ?? [];
}

export async function createMentorProject(input: MentorProjectInput): Promise<MentorProjectRow> {
  const supabase = getSupabaseClientOrThrow();
  const finalInput = input.sort_order === undefined
    ? { ...input, sort_order: await nextSortOrder("mentor_projects", input.mentor_id) }
    : input;
  const { data, error } = await supabase.from("mentor_projects").insert(finalInput).select("*").single();
  assertServiceResponse(error);
  return data;
}

export async function updateMentorProject(id: string, input: Updates<"mentor_projects">): Promise<MentorProjectRow> {
  const supabase = getSupabaseClientOrThrow();
  const { data, error } = await supabase.from("mentor_projects").update(input).eq("id", id).select("*").single();
  assertServiceResponse(error);
  return data;
}

export async function deleteMentorProject(id: string): Promise<void> {
  const supabase = getSupabaseClientOrThrow();
  const { error } = await supabase.from("mentor_projects").update({ deleted_at: new Date().toISOString() }).eq("id", id);
  assertServiceResponse(error);
}

export async function reorderMentorProjects(mentorId: string, orderedIds: string[]): Promise<void> {
  const supabase = getSupabaseClientOrThrow();
  await Promise.all(
    orderedIds.map((id, index) =>
      supabase.from("mentor_projects").update({ sort_order: index }).eq("id", id).eq("mentor_id", mentorId)
    )
  );
}

// ─── Certifications ───────────────────────────────────────────────────────────

export async function listMentorCertifications(mentorId: string): Promise<MentorCertificationRow[]> {
  const supabase = getSupabaseClientOrThrow();
  const { data, error } = await supabase
    .from("mentor_certifications")
    .select("*")
    .eq("mentor_id", mentorId)
    .is("deleted_at", null)
    .order("sort_order", { ascending: true });
  assertServiceResponse(error);
  return data ?? [];
}

export async function createMentorCertification(input: MentorCertificationInput): Promise<MentorCertificationRow> {
  const supabase = getSupabaseClientOrThrow();
  const finalInput = input.sort_order === undefined
    ? { ...input, sort_order: await nextSortOrder("mentor_certifications", input.mentor_id) }
    : input;
  const { data, error } = await supabase.from("mentor_certifications").insert(finalInput).select("*").single();
  assertServiceResponse(error);
  return data;
}

export async function updateMentorCertification(id: string, input: Updates<"mentor_certifications">): Promise<MentorCertificationRow> {
  const supabase = getSupabaseClientOrThrow();
  const { data, error } = await supabase.from("mentor_certifications").update(input).eq("id", id).select("*").single();
  assertServiceResponse(error);
  return data;
}

export async function deleteMentorCertification(id: string): Promise<void> {
  const supabase = getSupabaseClientOrThrow();
  const { error } = await supabase.from("mentor_certifications").update({ deleted_at: new Date().toISOString() }).eq("id", id);
  assertServiceResponse(error);
}

export async function reorderMentorCertifications(mentorId: string, orderedIds: string[]): Promise<void> {
  const supabase = getSupabaseClientOrThrow();
  await Promise.all(
    orderedIds.map((id, index) =>
      supabase.from("mentor_certifications").update({ sort_order: index }).eq("id", id).eq("mentor_id", mentorId)
    )
  );
}

// ─── Achievements ─────────────────────────────────────────────────────────────

export async function listMentorAchievements(mentorId: string): Promise<MentorAchievementRow[]> {
  const supabase = getSupabaseClientOrThrow();
  const { data, error } = await supabase
    .from("mentor_achievements")
    .select("*")
    .eq("mentor_id", mentorId)
    .is("deleted_at", null)
    .order("sort_order", { ascending: true });
  assertServiceResponse(error);
  return data ?? [];
}

export async function createMentorAchievement(input: MentorAchievementInput): Promise<MentorAchievementRow> {
  const supabase = getSupabaseClientOrThrow();
  const finalInput = input.sort_order === undefined
    ? { ...input, sort_order: await nextSortOrder("mentor_achievements", input.mentor_id) }
    : input;
  const { data, error } = await supabase.from("mentor_achievements").insert(finalInput).select("*").single();
  assertServiceResponse(error);
  return data;
}

export async function updateMentorAchievement(id: string, input: Updates<"mentor_achievements">): Promise<MentorAchievementRow> {
  const supabase = getSupabaseClientOrThrow();
  const { data, error } = await supabase.from("mentor_achievements").update(input).eq("id", id).select("*").single();
  assertServiceResponse(error);
  return data;
}

export async function deleteMentorAchievement(id: string): Promise<void> {
  const supabase = getSupabaseClientOrThrow();
  const { error } = await supabase.from("mentor_achievements").update({ deleted_at: new Date().toISOString() }).eq("id", id);
  assertServiceResponse(error);
}

export async function reorderMentorAchievements(mentorId: string, orderedIds: string[]): Promise<void> {
  const supabase = getSupabaseClientOrThrow();
  await Promise.all(
    orderedIds.map((id, index) =>
      supabase.from("mentor_achievements").update({ sort_order: index }).eq("id", id).eq("mentor_id", mentorId)
    )
  );
}
