-- Mentor Profile: real, structured content tables to replace the fabricated
-- data previously generated by src/features/mentor-profile/services/mentorProfileFactory.ts
-- (invented education/certifications/projects/experience/reviews attributed to fake students).
-- See docs/BUG_REPORT.md BUG-41 for the full writeup.

-- =========================================================================
-- 1. mentor_experience — real work-history entries, mentor-managed
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.mentor_experience (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    mentor_id       uuid NOT NULL REFERENCES public.mentor_profiles(id) ON DELETE CASCADE,
    company         text NOT NULL,
    company_logo_url text,
    role            text NOT NULL,
    starts_on       date NOT NULL,
    ends_on         date,
    is_current      boolean NOT NULL DEFAULT false,
    responsibilities text[] NOT NULL DEFAULT '{}',
    achievements    text[] NOT NULL DEFAULT '{}',
    sort_order      int NOT NULL DEFAULT 0,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz,
    created_by      uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    updated_by      uuid REFERENCES public.profiles(id) ON DELETE SET NULL,

    CONSTRAINT mentor_experience_dates_check CHECK (ends_on IS NULL OR ends_on >= starts_on)
);

CREATE INDEX IF NOT EXISTS idx_mentor_experience_mentor_sort
    ON public.mentor_experience(mentor_id, sort_order);

CREATE TRIGGER set_updated_at_mentor_experience
    BEFORE UPDATE ON public.mentor_experience
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.mentor_experience ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read mentor_experience" ON public.mentor_experience
    FOR SELECT USING (deleted_at IS NULL);
CREATE POLICY "Mentors manage own mentor_experience" ON public.mentor_experience
    FOR ALL USING (mentor_id = auth.uid()) WITH CHECK (mentor_id = auth.uid());
CREATE POLICY "Admins manage mentor_experience" ON public.mentor_experience
    FOR ALL USING (public.has_role('admin')) WITH CHECK (public.has_role('admin'));

-- =========================================================================
-- 2. mentor_projects — real portfolio projects, mentor-managed
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.mentor_projects (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    mentor_id       uuid NOT NULL REFERENCES public.mentor_profiles(id) ON DELETE CASCADE,
    title           text NOT NULL,
    description     text,
    image_file_id   uuid REFERENCES public.files(id) ON DELETE SET NULL,
    tech_stack      text[] NOT NULL DEFAULT '{}',
    industry        text,
    difficulty      text CHECK (difficulty IN ('Beginner','Intermediate','Advanced')),
    github_url      text,
    live_url        text,
    sort_order      int NOT NULL DEFAULT 0,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz,
    created_by      uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    updated_by      uuid REFERENCES public.profiles(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_mentor_projects_mentor_sort
    ON public.mentor_projects(mentor_id, sort_order);

CREATE TRIGGER set_updated_at_mentor_projects
    BEFORE UPDATE ON public.mentor_projects
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.mentor_projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read mentor_projects" ON public.mentor_projects
    FOR SELECT USING (deleted_at IS NULL);
CREATE POLICY "Mentors manage own mentor_projects" ON public.mentor_projects
    FOR ALL USING (mentor_id = auth.uid()) WITH CHECK (mentor_id = auth.uid());
CREATE POLICY "Admins manage mentor_projects" ON public.mentor_projects
    FOR ALL USING (public.has_role('admin')) WITH CHECK (public.has_role('admin'));

-- =========================================================================
-- 3. mentor_certifications — real issuer-verified credentials, mentor-managed
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.mentor_certifications (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    mentor_id       uuid NOT NULL REFERENCES public.mentor_profiles(id) ON DELETE CASCADE,
    name            text NOT NULL,
    issuer          text NOT NULL,
    issuer_logo_file_id uuid REFERENCES public.files(id) ON DELETE SET NULL,
    issue_date      date,
    credential_url  text,
    sort_order      int NOT NULL DEFAULT 0,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz,
    created_by      uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    updated_by      uuid REFERENCES public.profiles(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_mentor_certifications_mentor_sort
    ON public.mentor_certifications(mentor_id, sort_order);

CREATE TRIGGER set_updated_at_mentor_certifications
    BEFORE UPDATE ON public.mentor_certifications
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.mentor_certifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read mentor_certifications" ON public.mentor_certifications
    FOR SELECT USING (deleted_at IS NULL);
CREATE POLICY "Mentors manage own mentor_certifications" ON public.mentor_certifications
    FOR ALL USING (mentor_id = auth.uid()) WITH CHECK (mentor_id = auth.uid());
CREATE POLICY "Admins manage mentor_certifications" ON public.mentor_certifications
    FOR ALL USING (public.has_role('admin')) WITH CHECK (public.has_role('admin'));

-- =========================================================================
-- 4. mentor_achievements — real recognitions/awards, mentor-managed
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.mentor_achievements (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    mentor_id       uuid NOT NULL REFERENCES public.mentor_profiles(id) ON DELETE CASCADE,
    title           text NOT NULL,
    description     text,
    achieved_on     date,
    icon            text,
    sort_order      int NOT NULL DEFAULT 0,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz,
    created_by      uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    updated_by      uuid REFERENCES public.profiles(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_mentor_achievements_mentor_sort
    ON public.mentor_achievements(mentor_id, sort_order);

CREATE TRIGGER set_updated_at_mentor_achievements
    BEFORE UPDATE ON public.mentor_achievements
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.mentor_achievements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read mentor_achievements" ON public.mentor_achievements
    FOR SELECT USING (deleted_at IS NULL);
CREATE POLICY "Mentors manage own mentor_achievements" ON public.mentor_achievements
    FOR ALL USING (mentor_id = auth.uid()) WITH CHECK (mentor_id = auth.uid());
CREATE POLICY "Admins manage mentor_achievements" ON public.mentor_achievements
    FOR ALL USING (public.has_role('admin')) WITH CHECK (public.has_role('admin'));

-- =========================================================================
-- 5. meetings: add a real attendee column so a student's own booking is
--    visible/cancellable by them (previously only host/admin had any access)
-- =========================================================================
ALTER TABLE public.meetings
    ADD COLUMN IF NOT EXISTS attendee_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_meetings_attendee ON public.meetings(attendee_id);

-- Booking creation itself stays admin/host-only at the RLS layer (mirrors the
-- enrollments/enroll-free precedent) - the book-mentor-session Edge Function
-- uses the service-role key to insert after re-validating availability server-side.
CREATE POLICY "Attendees view own booked meetings" ON public.meetings
    FOR SELECT USING (attendee_id = auth.uid());
CREATE POLICY "Attendees cancel own booking" ON public.meetings
    FOR UPDATE USING (attendee_id = auth.uid())
    WITH CHECK (attendee_id = auth.uid() AND status = 'cancelled');

-- =========================================================================
-- 6. get_mentor_available_slots — expands a mentor's recurring weekly
--    `availability` template into concrete free slots for a date range,
--    excluding any that overlap an existing non-cancelled `meetings` row.
--    SECURITY DEFINER so it can read `meetings` (host-only RLS) without
--    exposing meeting details - it only ever returns free start/end pairs.
-- =========================================================================
CREATE OR REPLACE FUNCTION public.get_mentor_available_slots(
    p_mentor_id uuid,
    p_start_date date,
    p_end_date date,
    p_slot_minutes int DEFAULT 45
)
RETURNS TABLE (slot_start timestamptz, slot_end timestamptz)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_day date;
BEGIN
    IF p_end_date < p_start_date THEN
        RETURN;
    END IF;
    IF p_end_date - p_start_date > 60 THEN
        RAISE EXCEPTION 'Date range too large (max 60 days)';
    END IF;

    FOR v_day IN SELECT generate_series(p_start_date, p_end_date, interval '1 day')::date LOOP
        RETURN QUERY
        SELECT gs.slot_start, gs.slot_start + make_interval(mins => p_slot_minutes)
        FROM public.availability a
        CROSS JOIN LATERAL generate_series(
            (v_day + a.start_time)::timestamptz,
            (v_day + a.end_time)::timestamptz - make_interval(mins => p_slot_minutes),
            make_interval(mins => p_slot_minutes)
        ) AS gs(slot_start)
        WHERE a.user_id = p_mentor_id
          AND a.is_active = true
          AND a.deleted_at IS NULL
          AND a.day_of_week = EXTRACT(DOW FROM v_day)::int
          AND gs.slot_start > now()
          AND NOT EXISTS (
              SELECT 1 FROM public.meetings m
              WHERE m.host_id = p_mentor_id
                AND m.status <> 'cancelled'
                AND m.starts_at < gs.slot_start + make_interval(mins => p_slot_minutes)
                AND m.ends_at > gs.slot_start
          );
    END LOOP;
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_mentor_available_slots(uuid, date, date, int) TO authenticated;

COMMENT ON FUNCTION public.get_mentor_available_slots IS
    'Returns free bookable slots for a mentor by expanding their weekly availability template and excluding conflicts with existing non-cancelled meetings. Used by the mentor-booking flow; never exposes meeting details.';
