create table if not exists public.success_stories (
  id bigint generated by default as identity primary key,
  title text not null,
  job_role text,
  company_name text,
  image_url text,
  full_story text,
  package text,
  published boolean not null default false,
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.success_stories enable row level security;

create policy "Published success stories are viewable by everyone" on public.success_stories
  for select using (published = true);

create policy "Admins can manage success stories" on public.success_stories
  for all using (auth.jwt() ->> 'role' = 'admin');
